### ISSUE TITLE
Remove BarcodeDetector::options setter, or include context method for update them.

### ISSUE THREAD

**Issue by roipeker** [tuarua/Firebase-ANE#10]
This is just a suggestion as the "interfase" of the class becomes confusing otherwise.

`BarcodeDetector::options` is only passed to the context in the constructor, the setter seems pointless, as it only stores the variable but doesn't updates the context.

Even if the `VisionANE::barcodeDetector()` is a nice feature for lazy initialization and "singleton" access, but you can not modify the barcode options in later usages.

If possible, instead of removing the setter, pass the options to the context. 
Using a new _context.call() or as a  last param in `_context.call::"detect"` & `_context.call::"inputFromCamera"`

**Comment by tuarua** [comment]
TODO remove obsolete options setter.
API follows the actual MLKit API, API to remain unchanged otherwise. 
To update options will be able to redeclare the barcodeDetector as per MLKit API.

**Comment by tuarua** [comment]
Fixed in 0.0.8
