### ISSUE TITLE
feature request: improve BarcodeDetector::inputFromCamera()

### ISSUE THREAD

**Issue by roipeker** [tuarua/Firebase-ANE#11]
Having the versatility of `BarcodeDetector::detect()` with custom AS3 implementation using Camera.getCamera() && bitmapData is great, but is not performant and no autofocus.

`::inputFromCamera()` is really practical though, but going fullscreen blocks the entire app until it gets an event (which could never happen), there's no way to cancel/dispose the view.

A few ideas:

- I think that **adding a viewport Rectangle** with stage coordinates is a must here.
- Basic Torch API would be a GREAT addition to for this feature while capturing.
Makes sense to have a different ANE for that if possible, in order to use with a custom UI for ::detect() or other Firebase Vision APIs that requires camera access.

**Comment by roipeker** [comment]
Could you consider adding the viewport rectangle to fullscreen native camera ?

**Comment by tuarua** [comment]
0.0.9 now allows images and buttons to be added above the native camera view - see the updated example and changelog for details
