### ISSUE TITLE
Android, Analytics tracking_id not found for value.xml

### ISSUE THREAD

**Issue by roipeker** [tuarua/Firebase-ANE#14]
Following the wiki for Android,
[Configuring FirebaseANE](https://github.com/tuarua/Firebase-ANE/wiki/Configuring---FirebaseANE), I can't find any `tracking_id` field in **google-services.json** (nor id on the firebase console).

Is a required field to make analytics work on Android? I just commented the line in **values.xml**

**Comment by tuarua** [comment]
This tag is optional.
I believe it's related to Firebase accounts that have legacy Google Analytics.
Comment out if N/A
