### ISSUE TITLE
No sound for notification. How to change sound ?

### ISSUE THREAD

**Issue by iqbalpalemad** [tuarua/Firebase-ANE#20]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Yes
    
- **What version of the product are you using?**
     0.0.9

- **On what which device system?**
    - Lenovo vibe k5 note has no sound (android m) . But has sound in honor 9n(andoid O).

- **With which operating system?**
    - Android 6 (M)

- **From which operating system?**
    -Win10

- **Which IDE are you using?**
    - IntelliJ

- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**
    - build with air 32 on lenovo k5 has no sounf

- **What is the expected output? What do you see instead?**
    - expected to play sound. but no sound

- **Please provide any additional information below.**
    - when i build in lenvovo k5 Note , the notification has no sound . But in honor 9N which playes the default notification sound. In my app i need sound for all devices. also it would be good if i can set custom sound. how to do thids too.

- **Does this problem also occur in the Sample Application provided?**
- Yes

**Comment by tuarua** [comment]
Please explain how you are sending the notification.
I need full steps to reproduce.

**Comment by tuarua** [comment]
Please see https://github.com/tuarua/Firebase-ANE/wiki/Messaging---Get-Started#sending-test-message-with-postman for details on sending test messages.

Sound on Android 6 and 8 is working correctly for me. If Lenovo k5 has a problem then it is not a problem with the ANE but a problem with either the device or a bug in Firebase itself. This ANE is just a wrapper for Firebase. Google would have to fix this.
Custom sounds are not supported.
