### ISSUE TITLE
Where is release folder to download *.ane files by wget?

### ISSUE THREAD

**Issue by manjav** [tuarua/Firebase-ANE#22]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    e.g. 0.0.1

- **On what which device system?**
    - Nexus 5

- **With which operating system?**
    - Android 6

- **From which operating system?**
    -  Win10, 

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

- **Which version of AIR are you using?**
    - 31

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.

- **Does this problem also occur in the Sample Application provided?**

**Comment by manjav** [comment]
Also I can contribute for providing FD samples

**Comment by tuarua** [comment]
It's explained in the [wiki](https://github.com/tuarua/Firebase-ANE/wiki#downloading-required-files)

> These scripts download the FirebaseANEs and dependencies. eg:
> 
>  - example/ios_dependencies/*
>  - example/android_dependencies/com.google.firebase.firebase-firestore-17.0.1.ane
>  - native_extension/FirestoreANE/ane/FirestoreANE.ane
>  - native_extension/AnalyticsANE/ane/AnalyticsANE.ane
>  - etc ...
