### ISSUE TITLE
Is the InAppMessaging ANE working ?

### ISSUE THREAD

**Issue by smabed** [tuarua/Firebase-ANE#25]
I have downloaded your Firebase ANE's , i success to enable the Firebase Analytics ANE and its working for me ... GOOD JOB.

after that i try to enable the InAppMessaging and didn't success to do so, although i make all the needed according to your Wiki, and also compiled and installed your example on my android device and the inAppMessaging did work. the problem that i am getting token with null value from both your example app and my enabling app, and the TOKEN_REGRESHED not called, and i am getting no log at logcat regarding instance id, or any relevant message from Firebase Messgaing.

Is this still working ? anyone success to enable it and can share his solution?

**Comment by tuarua** [comment]
It works fine for me.
Please check again your app.xml configuration and the values.xml in META-INF/ANE/... folder have been set and applied.

In future please complete the issue questions properly. I have no idea what device you are running on, the version of the ANE, the version of AIR etc.
