### ISSUE TITLE
Messaging API forground/background receive

### ISSUE THREAD

**Issue by varadig** [tuarua/Firebase-ANE#27]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
Yes
    
- **What version of the product are you using?**
    - What version are you using?
latest: 0.3.0

- **On what which device system?**
    - Samsung S8, iPhoneX, iPad Pro etc?
Samsung J5

- **With which operating system?**
    - iOS 11, Android 7 etc?
Android 6.0.1

- **From which operating system?**
    - OSX, Win7, Win 8, Win10, etc?
OSX High Sierra

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
IntelliJ IDEA

- **Which version of AIR are you using?**
    - 29, 30.. etc?
32

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.
Simply question

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.

- **Does this problem also occur in the Sample Application provided?**

There is way to check, the FCM is came from when app is on background or is in foreground?

There is just the 
       ` this.messaging.addEventListener(MessagingEvent.ON_MESSAGE_RECEIVED, onMessageReceived);` event, and when the app is foreground, the event is triggered immediately, when the message arrived.
When the app is background, the event is triggered when I click the notification.

But I have to navigate the user some screen, when came from background.
When the user is in the application, I need to just warning tho got a new message.

Thanks

**Comment by tuarua** [comment]
The Messaging Event doesn't provide background or foreground status of the app.

You will need to use NativeApplication.nativeApplication.addEventListener(Event.ACTIVATE, onActivate); to determine if the user has just activated the app when the message arrives.

Eg.
You could say **if** Event.ACTIVATE triggered < 1 second before messageEvent received **then** the user has clicked on the message to bring the app to foreground.

**Comment by varadig** [comment]
thanks!
