### ISSUE TITLE
Error while compiling iOS app, while Android is working

### ISSUE THREAD

**Issue by varadig** [tuarua/Firebase-ANE#28]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
I think, yes.
    
- **What version of the product are you using?**
    - What version are you using?
0.3.0

- **On what which device system?**
    - Samsung S8, iPhoneX, iPad Pro etc?
iPhone 6s

- **With which operating system?**
    - iOS 11, Android 7 etc?
iOS 11.4.1

- **From which operating system?**
    - OSX, Win7, Win 8, Win10, etc?
OSx High Sierra

- **Which IDE are you using?**
I    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
Intellij IDEA

- **Which version of AIR are you using?**
    - 29, 30.. etc?
32

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.
Compilation fail

- **What is the expected output? What do you see instead?**

https://www.dropbox.com/s/lhoqseu3waazd12/Screenshot%202019-03-21%2007.56.28.png?dl=0

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.
https://www.dropbox.com/s/lhoqseu3waazd12/Screenshot%202019-03-21%2007.56.28.png?dl=0

https://www.dropbox.com/s/ugvjwbvi22gp0ko/Screenshot%202019-03-21%2007.58.51.png?dl=0

- **Does this problem also occur in the Sample Application provided?**
No

description

```
    <extensions>
        <extensionID>com.sbhave.nativeExtensions.zbar</extensionID>

        <extensionID>com.milkmangames.extensions.CoreMobile</extensionID>

        <extensionID>com.tuarua.frekotlin</extensionID>
        <extensionID>org.greenrobot.eventbus</extensionID>
        <extensionID>com.google.code.gson.gson</extensionID>
        <extensionID>com.android.support.support-v4</extensionID>
        <extensionID>com.google.android.gms.play-services-base</extensionID>

        <extensionID>com.google.firebase.firebase-analytics</extensionID>
        <extensionID>com.google.firebase.firebase-iid</extensionID>
        <extensionID>com.tuarua.firebase.FirebaseANE</extensionID>
        <extensionID>com.tuarua.firebase.AnalyticsANE</extensionID>


        <extensionID>com.tuarua.firebase.MessagingANE</extensionID>
        <extensionID>com.google.firebase.firebase-messaging</extensionID>

        <extensionID>com.tuarua.firebase.RemoteConfigANE</extensionID>
        <extensionID>com.google.firebase.firebase-config</extensionID>

        <!--<extensionID>org.jetbrains.kotlinx.kotlinx-coroutines-android</extensionID>-->


    </extensions>

```

```
<!-- iOS specific capabilities -->
    <iPhone>
        <!-- A list of plist key/value pairs to be added to the application Info.plist -->
        <InfoAdditions>
            <![CDATA[
            <key>MinimumOSVersion</key>
                <string>9.0</string>
            <key>FirebaseAutomaticScreenReportingEnabled</key>
                <false/>
            <key>UIBackgroundModes</key>
            <array>
                <string>remote-notification</string>
            </array>
            <key>UIDeviceFamily</key>
            <array>
                <string>1</string>
                <string>2</string>
            </array>
            ]]>
        </InfoAdditions>

        <!-- A list of plist key/value pairs to be added to the application Entitlements.plist -->
        <Entitlements>
            <![CDATA[
                <key>keychain-access-groups</key>
                <array>
                    <string>SRUGWKQ769.*</string>
                </array>
                <key>get-task-allow</key>
                <true/>
                <key>application-identifier</key>
                <string>SRUGWKQ769.hu.devinflow.fst2b.guest</string>
                <key>com.apple.developer.team-identifier</key>
                <string>SRUGWKQ769</string>
                <key>aps-environment</key>
                <string>development</string>
                ]]>

        </Entitlements>

        <!-- Display Resolution for the app (either "standard" or "high"). Optional. Default "standard" -->
        <requestedDisplayResolution>high</requestedDisplayResolution>
        <!-- Forcing Render Mode CPU for the devices mentioned. Optional  -->
        <!--<forceCPURenderModeForDevices></forceCPURenderModeForDevices> -->
        <!-- File containing line separated list of external swf paths. These swfs won't be packaged inside the application
        and corresponding stripped swfs will be output in externalStrippedSwfs folder. -->
        <!--<externalSwfs></externalSwfs> -->
    </iPhone>

```

**Comment by tuarua** [comment]
Fabric.io framework is packaged as part of CrashlyticsANE
It appears it may now also needed by other parts of Firebase.
Can you include CrashlyticsANE in your <extensions> You don't need to init the CrashlyticsANE functionality, it just needs to be there for linking.

I will look at adding it to FirebaseANE (the core ANE) in the next release.

**Comment by varadig** [comment]
Thank You, I will try it today. And thanks for the fantastic ane of this and the quick response all the issues! This projecr is what really need to be support. Today im gona send some donation!!!!
