### ISSUE TITLE
Enable_bitcode issue in FreSwift framework

### ISSUE THREAD

**Issue by vizgl** [tuarua/Firebase-ANE#29]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
yes
    
- **What version of the product are you using?**
    - What version are you using?
   0.3.0

- **On what which device system?**
    iPhoneX

- **With which operating system?**
    - iOS 12

- **From which operating system?**
    - OSX

- **Which IDE are you using?**
    cmd line

- **Which version of AIR are you using?**
   32.109 beta

- **What steps will reproduce the problem?**
trying package game through adt with -embedBitcode yes flag

- **What is the expected output? What do you see instead?**
Got error:
ld: '/var/folders/nm/vfhxwlvn3zd54gqgcrc2kbxc0000gn/T/0c522990-e1fd-47e2-9d51-da9bea11474d/Frameworks/FreSwift.framework/FreSwift' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/var/folders/nm/vfhxwlvn3zd54gqgcrc2kbxc0000gn/T/0c522990-e1fd-47e2-9d51-da9bea11474d/Frameworks/FreSwift.framework/FreSwift' for architecture arm64
ld: '/var/folders/nm/vfhxwlvn3zd54gqgcrc2kbxc0000gn/T/0c522990-e1fd-47e2-9d51-da9bea11474d/Frameworks/FreSwift.framework/FreSwift' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/var/folders/nm/vfhxwlvn3zd54gqgcrc2kbxc0000gn/T/0c522990-e1fd-47e2-9d51-da9bea11474d/Frameworks/FreSwift.framework/FreSwift' for architecture armv7
Compilation failed while executing : ld64

- **Please provide any additional information below.**
without -embedBitcode yes flag all works, except crashlytics

- **Does this problem also occur in the Sample Application provided?**
don't know

**Comment by tuarua** [comment]
This is an expected compile error - none of my ANEs have bitcode enabled.
From AIR28 release notes https://helpx.adobe.com/flash-player/release-note/fp_28_air_28_release_notes.html
> Embedding bitcode requires that all your ANEs also include bitcode. If not present, adt can throw packaging errors such as the following:

Please explain what you mean by this. Saying something _doesn't work_ is not useful information.

> without -embedBitcode yes flag **all works, except crashlytics**

**Comment by vizgl** [comment]
> This is an expected compile error - none of my ANEs have bitcode enabled.
> From AIR28 release notes https://helpx.adobe.com/flash-player/release-note/fp_28_air_28_release_notes.html
> 
> > Embedding bitcode requires that all your ANEs also include bitcode. If not present, adt can throw packaging errors such as the following:
> 
> Please explain what you mean by this. Saying something _doesn't work_ is not useful information.
> 
> > without -embedBitcode yes flag **all works, except crashlytics**

Analytics is works and crashlytics events are sent, but I can't see crash logs because dSYM file is missing. I trying to create it by flag  -embedBitcode yes

**Comment by tuarua** [comment]
Using -embedBitcode is not related to dSYM files.
A dSYM file is created for me using IntelliJ as my IDE. You'll need to search Google for why the dSYM file is not created when using adt from command line. Is not a bug in the ANE.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/12083217/55275150-d9627500-52d9-11e9-9d2c-e49d893c12bd.png">
