### ISSUE TITLE
type mistake in wiki

### ISSUE THREAD

**Issue by pingwinator** [tuarua/Firebase-ANE#33]
Hi. I can't submit a suggestion in the [wiki](https://github.com/tuarua/Firebase-ANE/wiki/Performance---Disable-Performance-Monitoring)
So I will leave it here. Please, update the following section:

> To disable Performance Monitoring, but allow your app to enable it at runtime, set firebase_performance_collection_enabled to `true` in your app xml's Info.plist file.

the value should be `false`

**Comment by tuarua** [comment]
Thanks. Fixed.
