### ISSUE TITLE
dx tool failed

### ISSUE THREAD

**Issue by varadig** [tuarua/Firebase-ANE#36]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
    yes
- **What version of the product are you using?**
    - What version are you using?
    e.g. 0.0.1
latest 0.6.0

- **On what which device system?**
    - Samsung S8, iPhoneX, iPad Pro etc?
build error

- **With which operating system?**
    - iOS 11, Android 7 etc?
build error

- **From which operating system?**
    - OSX, Win7, Win 8, Win10, etc?
MacOS 10.13.2

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
IntelliJ

- **Which version of AIR are you using?**
    - 29, 30.. etc?
32

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.
Work it some month ago, now I update the anes and got the error.

- **What is the expected output? What do you see instead?**
`dx tool failed:<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/google/firebase/firebase_analytics/DummyANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/tuarua/firebase/AnalyticsANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.comma<br>nd.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing org/greenrobot/eventbus/DummyANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/tuarua/firebase/FirebaseANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/google/android/gms/play_services_base/DummyANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.<br>dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/google/firebase/firebase_config/DummyANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/adobe/air/TRActivityResultCallback.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/google/firebase/firebase_messaging/DummyANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at<br> com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/tuarua/firebase/MessagingANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/android/support/support_v4/DummyANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/tuarua/firebase/RemoteConfigANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpe<br>ner.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/tuarua/firebase/CrashlyticsANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/google/firebase/firebase_iid/DummyANE.class<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	at com.android.dx.command.Main.main(Main.java:106)<br>...while parsing com/google/code/gson/gson/DummyANE.class<br>14 errors; aborting
`

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.
https://www.dropbox.com/s/dvamh4g9iif74bz/Screenshot%202019-09-24%2011.15.56.png?dl=0
- **Does this problem also occur in the Sample Application provided?**

**Comment by tuarua** [comment]
See https://github.com/tuarua/Firebase-ANE/wiki#air-32--33

**Comment by varadig** [comment]
I dont know, how to forgot this, or when replace back (to the original dx.jar) but re download and replace is solve the issue.
Thanks!
