### ISSUE TITLE
google sign in error 10- 10

### ISSUE THREAD

**Issue by benkhachouch** [tuarua/Firebase-ANE#4]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
YES
    - Follow the instructions provided before raising an issue.
OK
    
- **What version of the product are you using?**
1
    - What version are you using?
    adobe air 30.0

- **On what which device system?**
    - samsung galaxy s6

- **With which operating system?**
    -  Android 7 

- **From which operating system?**
    - Win10, 

- **Which IDE are you using?**
    -  Flash Builder

- **Which version of AIR are you using?**
    - 30

- **What steps will reproduce the problem?**
    - from the firebase example: I got for ggogle signin error 10-10

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.

- **Does this problem also occur in the Sample Application provided?**
yes

**Comment by tuarua** [comment]
Error 10 is DEVELOPER_ERROR: "The application is misconfigured."

https://github.com/tuarua/Firebase-ANE/blob/0de3da581da96cdd5ace9dcda480a7021117a42d/native_extension/GoogleSignInANE/src/com/tuarua/google/signin/GoogleSignInStatusCode.as#L20

Please follow and complete steps 4&5 in the **Before you begin** section
https://firebase.google.com/docs/auth/android/google-signin

**Comment by benkhachouch** [comment]
Thanks.
