### ISSUE TITLE
Firestore component registarar

### ISSUE THREAD

**Issue by RepeZero** [tuarua/Firebase-ANE#40]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    e.g. 0.0.1
0.6.0
- **On what which device system?**
    - Samsung S8, iPhoneX, iPad Pro etc?

- **With which operating system?**
    - iOS 11, Android 7 etc?

- **From which operating system?**
    - OSX, Win7, Win 8, Win10, etc?

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

- **Which version of AIR are you using?**
    - 29, 30.. etc?

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.

- **Does this problem also occur in the Sample Application provided?**

Firebase needs com.google.firebase.components.ComponentRegistrar in manifest.xml.
Please add to the wiki 
for example, Firestore needs

			<meta-data #android:name="com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar"
			android:value="com.google.firebase.components.ComponentRegistrar"/>

**Comment by tuarua** [comment]
done
https://github.com/tuarua/Firebase-ANE/wiki/Firestore---Configuring-the-ANE#android
