### ISSUE TITLE
Missing dependency: com.google.android.gms.play-services-measurement

### ISSUE THREAD

**Issue by DQvsRA** [tuarua/Firebase-ANE#44]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
  Yes    

- **What version of the product are you using?**
    0.12.0

- **On what which device system?**
    I can't compile

- **With which operating system?**
    I'm targeting Android

- **From which operating system?**
    OSX

- **Which IDE are you using?**
    IntelliJ

- **Which version of AIR are you using?**
    33.1.1

- **What steps will reproduce the problem?**
   After running `bash get_android_dependencies.sh` not all dependencies can be found in android_dependencies folder

- **What is the expected output? What do you see instead?**
I wish to have com.google.android.gms.play-services-measurement-xxx.ane

- **Please provide any additional information below.**
    Take a look at: get_android_dependencies.log

- **Does this problem also occur in the Sample Application provided?**
    Yes

Log file:
[get_android_dependencies.log](https://github.com/tuarua/Firebase-ANE/files/4914616/get_android_dependencies.log)

**Comment by tuarua** [comment]
I have updated the bash script to fix the missing reference
