### ISSUE TITLE
new FacebookAuthCredential(accessToken:String)

### ISSUE THREAD

**Issue by benkhachouch** [tuarua/Firebase-ANE#5]
How get accessToken?
Have you an example?
Thanks.

Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    e.g. 0.0.1

- **On what which device system?**
    - Samsung S8, iPhoneX, iPad Pro etc?

- **With which operating system?**
    - iOS 11, Android 7 etc?

- **From which operating system?**
    - OSX, Win7, Win 8, Win10, etc?

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

- **Which version of AIR are you using?**
    - 29, 30.. etc?

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information. Screengrabs.

- **Does this problem also occur in the Sample Application provided?**

**Comment by tuarua** [comment]
Issue Tracker is for bugs only
