### ISSUE TITLE
The extension context does not have a method with the name init.

### ISSUE THREAD

**Issue by goodier** [tuarua/Firebase-ANE#58]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Yes, I've been reading Wiki for 5 days

- **What version of the product are you using?**
    - version 0.20.0
    
- **On what which device  #system?**
    - Samsung S7, Samsung S8

- **With which operating system?**
    - Android 12

- **From which operating system?**
    - Win11

- **Which IDE are you using?**
    - Animate

- **Which version of AIR are you using?**
    - Harman AIR SDK available is AIR 50.1.1.2

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.

(https://github.com/tuarua/AIR-Tools/) installed

```
{
  "name": "firebase-sample",
  "version": "0.20.0",
  "appDescriptor": "src/Main-app.xml",
  "variables": {
    "firebase_associated_domain": "xxxx.app.goo.gl",
    "firebase_scheme_name": "",
    "firebase_scheme_url": "",
    "onesignal_app_id": "",
    "onesignal_google_project_number": ""
  },
  "airDotPrefix": false,
  "repository": {
    "url": "https://tuarua.github.io/air/air_packages.json"
  },
  "dependencies": {
    "com.tuarua.firebase.FirebaseANE": "0.20.0",
    "com.tuarua.firebase.AnalyticsANE": "0.20.0",
    "com.tuarua.firebase.AuthANE": "0.20.0",
    "com.tuarua.firebase.DynamicLinksANE": "0.20.0",
    "com.tuarua.firebase.FirestoreANE": "0.20.0",
    "com.tuarua.firebase.MessagingANE": "0.20.0",
    "com.tuarua.firebase.PerformanceANE": "0.20.0",
    "com.tuarua.firebase.RemoteConfigANE": "0.20.0",
    "com.tuarua.firebase.StorageANE": "0.20.0",
    "com.tuarua.firebase.CrashlyticsANE": "0.20.0",
    "com.tuarua.google.GoogleSignInANE": "0.20.0",
    "com.tuarua.OneSignalANE": "0.20.0"
  }
}
```
Copied files from AIRSDK_additions to the appropriate folders in my AIRSDK.
As a result, I get an error.
I've been suffering for 6 days already, my nerves are already giving up.

```
[SWF] com.tuarua.firebase.AnalyticsANE - 8449 байт после распаковки
[SWF] com.tuarua.firebase.FirebaseANE - 107181 байт после распаковки
[SWF] androidx.browser.browser - 751 байт после распаковки
[SWF] com.tuarua.firebase.AuthANE - 18896 байт после распаковки
[SWF] com.google.firebase.firebase-auth-ktx - 751 байт после распаковки
[SWF] com.google.firebase.firebase-components - 751 байт после распаковки
[SWF] com.google.firebase.firebase-firestore-ktx - 751 байт после распаковки
[SWF] com.onesignal.OneSignal - 751 байт после распаковки
[SWF] com.tuarua.firebase.CrashlyticsANE - 3364 байт после распаковки
[Starling] Context ready. Display Driver: DirectX11 (Standard Extended)
ArgumentError: Error #3500: The extension context does not have a method with the name init.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua::Firebase()[/Users/eoinlandy/flash/Firebase-ANE/native_extension/src/com/tuarua/Firebase.as:20]
	at com.tuarua::Firebase$/init()[/Users/eoinlandy/flash/Firebase-ANE/native_extension/src/com/tuarua/Firebase.as:29]
	at StarlingRoot/start()[C:\Users\USER\Desktop\example\src\StarlingRoot.as:69]
	at Function/<anonymous>()[C:\Users\USER\Desktop\example\src\Main.as:34]
	at starling.events::EventDispatcher/invokeEvent()[/Users/redge/Development/starling/starling/src/starling/events/EventDispatcher.as:155]
	at starling.events::EventDispatcher/dispatchEvent()[/Users/redge/Development/starling/starling/src/starling/events/EventDispatcher.as:126]
	at starling.events::EventDispatcher/dispatchEventWith()[/Users/redge/Development/starling/starling/src/starling/events/EventDispatcher.as:207]
	at starling.core::Starling/initializeRoot()[/Users/redge/Development/starling/starling/src/starling/core/Starling.as:374]
	at starling.core::Starling/initialize()[/Users/redge/Development/starling/starling/src/starling/core/Starling.as:362]
	at starling.core::Starling/onContextCreated()[/Users/redge/Development/starling/starling/src/starling/core/Starling.as:595]
[FirebaseANE] Unloading ANE...
[AnalyticsANE] Unloading ANE...
[FirestoreANE] Unloading ANE...
[StorageANE] Unloading ANE...
[RemoteConfigANE] Unloading ANE...
[AuthANE] Unloading ANE...
[PerformanceANE] Unloading ANE...
[MessagingANE] Unloading ANE...
[OneSignalANE] Unloading ANE...
[DynamicLinksANE] Unloading ANE...
[CrashlyticsANE] Unloading ANE...
```

- **Does this problem also occur in the Sample Application provided?**

If we take an example from the Wiki

import com.tuarua.google.GoogleSignInANE;
import com.tuarua.google.signin.events.GoogleSignInEvent;
private var googleSignIn:GoogleSignInANE;
To launch the Google Sign In screen:
googleSignIn = GoogleSignInANE.googleSignIn;
googleSignIn.addEventListener(GoogleSignInEvent.SIGN_IN, onGoogleSignIn);
googleSignIn.addEventListener(GoogleSignInEvent.ERROR, onGoogleSignIn);
googleSignIn.signIn();

I get an error -
Could not find the definition of com.tuarua.google:GoogleSignInANE.

***********************
Please help me, I need at least GoogleSignInANE for android only?

**Comment by goodier** [comment]
Please provide the latest support page for this product.
My "animate" swears at FirebaseANEContext.context.call("init")
The extension context does not have a method with the name init.

**Comment by tuarua** [comment]
That's usually caused by Main.xml not being setup correctly.
https://github.com/tuarua/Firebase-ANE/issues/39
I should note I don't use or have an Animate subscription.

It would probably be better for you to look at the commercial Firebase product from Distriqt.

https://airnativeextensions.com/extension/com.distriqt.Firebase 

I do plan to update the Firebase ANE and others but am constrained by time and can't offer you the one-to-one support you expect.
