### ISSUE TITLE
Can't compile iOS

### ISSUE THREAD

**Issue by roipeker** [tuarua/Firebase-ANE#9]
Trying to use Barcode with these ANEs:

- com.tuarua.firebase.FirebaseANE
- com.tuarua.firebase.VisionANE
- com.tuarua.firebase.VisionBarcodeANE

I'm getting this error on compilation:

`ld: library not found for -lstdc++ Compilation failed while executing : ld64`

merge both zips in /ios_dependencies and put it on "."
[https://github.com/tuarua/Swift-IOS-ANE/releases/download/2.5.0/ios_dependencies.zip](https://github.com/tuarua/Swift-IOS-ANE/releases/download/2.5.0/ios_dependencies.zip)
[https://github.com/tuarua/Firebase-ANE/releases/download/0.0.7/ios_dependencies.zip](https://github.com/tuarua/Firebase-ANE/releases/download/0.0.7/ios_dependencies.zip)

Also applied the mod to AIR SDK (31.0.0.96)
[https://github.com/tuarua/Swift-IOS-ANE/releases/download/2.5.0/AIRSDK_additions.zip](https://github.com/tuarua/Swift-IOS-ANE/releases/download/2.5.0/AIRSDK_additions.zip)

**Comment by roipeker** [comment]
Maybe i'm missing a file in the _ios_dependencies (155,9 MB)_ ... 
This is the file list I have:

- GoogleMVTextDetectorResources.bundle
- GoogleSignIn.bundle
- simulator/Frameworks/SwiftyJSON.framework/
- simulator/Frameworks/libswiftCoreImage.dylib
- simulator/Frameworks/libswiftObjectiveC.dylib
- simulator/Frameworks/libswiftCore.dylib
- simulator/Frameworks/libswiftCoreGraphics.dylib
- simulator/Frameworks/libswiftUIKit.dylib
- simulator/Frameworks/libswiftMetal.dylib
- simulator/Frameworks/libswiftDispatch.dylib
- simulator/Frameworks/libswiftos.dylib
- simulator/Frameworks/libswiftCoreFoundation.dylib
- simulator/Frameworks/FreSwift.framework
- simulator/Frameworks/libswiftDarwin.dylib
- simulator/Frameworks/libswiftQuartzCore.dylib
- simulator/Frameworks/libswiftCoreAudio.dylib
- simulator/Frameworks/libswiftAVFoundation.dylib
- simulator/Frameworks/libswiftFoundation.dylib
- simulator/Frameworks/libswiftCoreMedia.dylib
- simulator/Frameworks/libswiftCoreLocation.dylib
- simulator/Frameworks/libswiftsimd.dylib
- device/Frameworks/SwiftyJSON.framework/
- device/Frameworks/libswiftCoreImage.dylib
- device/Frameworks/libswiftObjectiveC.dylib
- device/Frameworks/libswiftCore.dylib
- device/Frameworks/libswiftCoreGraphics.dylib
- device/Frameworks/libswiftUIKit.dylib
- device/Frameworks/libswiftMetal.dylib
- device/Frameworks/libswiftDispatch.dylib
- device/Frameworks/libswiftos.dylib
- device/Frameworks/libswiftCoreFoundation.dylib
- device/Frameworks/FreSwift.framework/
- device/Frameworks/libswiftDarwin.dylib
- device/Frameworks/libswiftQuartzCore.dylib
- device/Frameworks/libswiftCoreAudio.dylib
- device/Frameworks/libswiftAVFoundation.dylib
- device/Frameworks/libswiftFoundation.dylib
- device/Frameworks/libswiftCoreMedia.dylib
- device/Frameworks/libswiftCoreLocation.dylib
- device/Frameworks/libswiftsimd.dylib
- gRPCCertificates.bundle/
- GPPACLPickerResources.bundle
- GoogleMVFaceDetectorResources.bundle
- GINInviteResources.bundle

**Comment by roipeker** [comment]
I'm getting this error when compile for ios-debug:

```
unexpected failure: Negative seek offset
java.io.IOException: Negative seek offset
	at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:587)
	at com.adobe.air.ipa.IPASigner.prepareToSignFramework(IPASigner.java:200)
	at com.adobe.air.ipa.IPAOutputStream.finalizeFrameworkSig(IPAOutputStream.java:1653)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java:111)
	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java:297)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java:696)
	at com.adobe.air.ADT.run(ADT.java:485)
	at com.adobe.air.ADT.main(ADT.java:535)
...
```

And this for Simulator:

```
ld: library not found for -lstdc++
Compilation failed while executing : ld64

ADT command line:
...
```

**Comment by roipeker** [comment]
Please, if you need more info, lemme know. 
Seems like the files in `/Firebase-ANE/releases/download/0.0.7/ios_dependencies.zip` is breaking the compilation.

**Comment by tuarua** [comment]
Device java error:

Please delete these 2 files

1. device/Frameworks/libswiftCoreLocation.dylib
2. simulator/Frameworks/libswiftCoreLocation.dylib

Download updated
https://github.com/tuarua/Firebase-ANE/releases/download/0.0.7/ios_dependencies.zip
Copy these 2 files into corresponding folder

1. device/Frameworks/llibswiftAccelerate.dylib
2. simulator/Frameworks/llibswiftAccelerate.dylib

There was a naming problem when I zipped the files, renamed the wrong library (location is not even used)

**Comment by tuarua** [comment]
Simulator
AIR does not support Xcode10 Simulator yet.
Should be in AIR32

https://forums.adobe.com/thread/2522790

**Comment by roipeker** [comment]
Thanks so much for the fix. The vision ane works beautifuly. But all the setup process is a pain for sure :)

Can i recommend for future releases to include the anes in the same intellij dir project (maybe copy in an anes dir) cause the paths get corrupted otherwise showing $DOCUMENTS$ (Like an absolute parent path), so as i open the project i get over 30 errors of corrupted “links”

**Comment by roipeker** [comment]
After the updated zip, I was able to compile for iOS.
I will close the issue.
Thanks!
